spring:
  profiles:
    active: produ
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
server:
  port: ${PORT}

